print("Today's date?\n")
date = input()
print("Breakfast calories?\n")
breakfast_calories = int(input())
print("Lunch calories?\n")
lunch_calories = int(input())
print("Dinner calories?\n")
dinner_calories = int(input())
print("Snack calories")
snack_calories = int(input())
total = breakfast_calories + lunch_calories + dinner_calories + snack_calories
print("Calorie content for " + date + ": " + str(total))